MOD_ANCHOR_N  = "MOD_ANCHOR_N";
MOD_ANCHOR_E  = "MOD_ANCHOR_E";
MOD_ANCHOR_S  = "MOD_ANCHOR_S";
MOD_ANCHOR_W  = "MOD_ANCHOR_W";
MOD_ANCHOR_NE = "MOD_ANCHOR_NE";
MOD_ANCHOR_SE = "MOD_ANCHOR_SE";
MOD_ANCHOR_SW = "MOD_ANCHOR_SW";
MOD_ANCHOR_NW = "MOD_ANCHOR_NW";

MOD_BIND_NONE       = "case MOD_BIND_NONE";
MOD_BIND_MIDI       = "case MOD_BIND_MIDI";
MOD_BIND_KNOB       = "case MOD_BIND_KNOB";
MOD_BIND_FOOTSWITCH = "case MOD_BIND_FOOTSWITCH";
