name: irc

on: [push]

jobs:
  notification:
    runs-on: ubuntu-latest
    name: IRC notification
    steps:
      - name: Format message
        id: message
        run: |
          echo "message=${{ github.actor }} pushed $(echo '${{ github.event.commits[0].message }}' | head -n 1) ${{ github.event.commits[0].url }}" >> $GITHUB_OUTPUT
      - name: IRC notification
        uses: Gottox/irc-message-action@v2
        with:
          channel: '#modaudio'
          nickname: modaudio-bot
          message: ${{ steps.message.outputs.message }}
