name: unittest

on: [push, pull_request]

jobs:
  unittest:
    runs-on: ubuntu-22.04
    name: unittest
    steps:
      - uses: actions/checkout@v3
      - name: Install virtualenv
        run: |
          sudo apt install python3-virtualenv
      - name: Setup utils
        run: |
          sudo apt install python3-dev build-essential libasound2-dev libjack-jackd2-dev liblilv-dev libjpeg-dev zlib1g-dev
          make -C utils
      - name: Setup unittest
        run: |
          virtualenv modui-env
          source modui-env/bin/activate
          pip3 install -r requirements.txt
          # pytest
          pip3 install pytest pytest-cov
          sed -i -e 's/collections.MutableMapping/collections.abc.MutableMapping/' modui-env/lib/python3.10/site-packages/tornado/httputil.py
          # mod
          python3 setup.py develop
      - name: Run unittest
        run: |
          virtualenv modui-env
          source modui-env/bin/activate
          pytest --cov=mod --cov-report=html --cov-report=term --cov-report=xml
      - name: Archive coverage files
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: |
            .coverage
            htmlcov/**
            cobertura.xml
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '15 30'
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md